version: '3'
services:
  front:
    container_name: client
    build:
      context: ./client
 
    ports:
      - "3000:3000"

    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules

  server:
    container_name: server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./server
    
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules

    ports:
      - '5000:5000'

  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: webtempsreel
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_USER: ${POSTGRES_USER:-root}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-root}
      ADMINER_DEFAULT_TYPE: postgresql
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: ${POSTGRES_DB:-database}

volumes:
  database_data:
